version: '3'
services:
  db: 
    container_name: db_fga_inova_project_service
    image: mongo
    ports:
      - ":27028"
    command: mongod --quiet --logpath /dev/null

  api:
    container_name: backend_fga_inova_project
    build: .
    restart: always
    command: npm start
    ports:
      - "4444:4444"
    depends_on:
      - db
    volumes:
      - .:/app
    